apiVersion: apps/v1
kind: Deployment
metadata:
  name: bago-backend-2
  labels:
    app: bago-backend-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bago-backend-2
  template:
    metadata:
      labels:
        app: bago-backend-2
    spec:
      containers:
        - name: bago-backend-2
          image: josanbaq7/backbagoimage2
          ports:
            - containerPort: 9090